### ISSUE TITLE
Move project

### ISSUE THREAD

**Issue by daniviga** [opengisch/qgis-server-docker#64]
Since project is unmaintained on the @gem/gem-developers side, wouldn't it make sense to move it under opengis.ch or qgis.org?

@mbernasocchi @pslh ?

**Comment by pslh** [comment]
I am not in favour of moving this repository since we rely on the GitActions publishing to the OpenQuake account on DockerHub.  If OpenGIS.ch wish to make an official fork and use that as the reference, we have no objections.  Happy to discuss further.

**Comment by mbernasocchi** [comment]
hi @daniviga, we'd be very open to take it over if @pslh agrees, we've been the only ones maintaining and adding features to it since you left GEM.

**Comment by mbernasocchi** [comment]
there where discussions as wel about making this the "official" QGIS server docker. I need to restart those. The point @pslh mentioned above would stand in that case as well.

**Comment by timlinux** [comment]
+1 from me to make it official

**Comment by daniviga** [comment]
On the governance I can't say anything, anymore :) it's up to @pslh 

What I would suggest is that either GEM or the Opengis guys (if authorized  by GEM) do the merges to master; I would personally prefer to avoid that, for correctness to both the former and current employers. I have merged a couple of PRs that were left un-merged since 2020, but I will not touch it anymore.

**Comment by mbernasocchi** [comment]
@pslh absolutely yes please see #71

**Comment by 3nids** [comment]
@pslh could you start the transfer to opengisch ?
You can directly create a fork afterwards.

**Comment by pslh** [comment]
@3nids @mbernasocchi  - we are ready to transfer, but github tells me: "You don’t have the permission to create public repositories on opengisch"

> @pslh could you start the transfer to opengisch ? You can directly create a fork afterwards.

**Comment by nastasi-oq** [comment]
@3nids @mbernasocchi please, give permission to me permission to proceed with transfer.

**Comment by 3nids** [comment]
@pslh the alternative is to give me full admin rights on this repo only, can you do this?

**Comment by 3nids** [comment]
otherwise we need to give you full access to opengisch org.

**Comment by nastasi-oq** [comment]
> @pslh the alternative is to give me full admin rights on this repo only, can you do this?

I try.

**Comment by nastasi-oq** [comment]
> @pslh the alternative is to give me full admin rights on this repo only, can you do this?

Done, try to move it.

**Comment by nastasi-oq** [comment]
> otherwise we need to give you full access to opengisch org.

@3nids done, you can try to move ti.

**Comment by nastasi-oq** [comment]
> @pslh the alternative is to give me full admin rights on this repo only, can you do this?

@3nids done, you can try to transfer it.

**Comment by 3nids** [comment]
@pslh done, thanks a lot

**Comment by mbernasocchi** [comment]
@3nids @nastasi-oq @pslh Thanks a lot for making this happen!
